import React, {useState, useEffect} from "react";
import '../App/App.css'

// importing a random value from a non-React file to avoid Strict Mode comps. 
//import {pos} from "../../index";
// import {indexes} from "../../index";

function GCocktailData ({data, 
    setData, 
    iURL, 
    lookupURL, 
    individURL, 
    setIndividURL, 
    spirit,
    setMainIng,
    setIng2,
    setIng3,
    setServeInst,
    recipe}) {
    // RECIPE = INGREDIENTS/METHOD, HAS A DEFAULT SETTING BUT NEEDS TO BE UPDATED 
    // DATA = COCKTAIL ID NUMBER, NEEDS TO BE UPDATED IN DATA
    // SUGGESTION = COCKTAIL NAME GENERATED BY APP
    const [suggestion, setSuggestion] = useState("..."); // cocktail itself

    // come back to this - if/statement around useEffect

    useEffect(() => {
        console.log("hello")
    fetch(`https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=${spirit}`)
    .then(res => {
        return res.json()
    })
    .then(data => {
        console.log("kacper")
        let suggestionList = data.drinks;
        let pos = 0
        setData(suggestionList[pos].idDrink);
        setSuggestion(suggestionList[pos].strDrink);
        setIndividURL(`${iURL}${suggestionList[pos].idDrink}`)
        console.log(individURL)
        setMainIng(`You will need: 1) absolutely loads of ${recipe[0].strIngredient1}  `);
        setIng2(` 2) a healthy dash of ${recipe[0].strIngredient2}, `);
        setIng3( ` & finally, 3) a light sprinkling of ${recipe[0].strIngredient3}.`);
        setServeInst(` Please serve me in a ${recipe[0].strGlass}. Enjoy! `)          
},[])
});

console.log("emma")
    return(
        <div className="recipeCard">
            <h2 className="introText" id="recipeIntro">Your suggestion is: </h2>
            <h2 id="recipeIntro2">{suggestion}</h2>
         </div>
    )
}
export default GCocktailData
